### PR TITLE
hot fix for post pusher log directory error

### PR DESCRIPTION
**Pull request by powerwlsl**
While I was working on adding seed file on Newswire, I ran into this error.
```
/usr/local/bundle/gems/post_pusher-1.2.0/lib/post_pusher/rake_task_runner.rb:37:in `mkdir': No such file or directory @ dir_s_mkdir - /home/plm/service/log/post_push (Errno::ENOENT)
```

It was unable to create `/home/plm/service/log/post_push` directory because `/home/plm/service/log` didn't exist. To fix this, I updated `Dir.mkdir` to `FileUtils.mkdir_p` so that we can recursively create a directory.

Tested on forked branch(https://github.com/powerwlsl/post_pusher) and it worked.

The full error message can be found here.
[log.txt](https://github.com/patientslikeme/post_pusher/files/6144377/log.txt)

### CODE REVIEW

**Comment by bryanalves** [comment]
Hi,

This repository is public, and that log file contains lots of information that might be better kept private, such as

* AWS account information
* deployment infrastructure details
* versions used of internal tools
* internal names of products
* internal dns information
* internal database structure information

**Comment by powerwlsl** [comment]
Hi @bryanalves, I reverted it and opened a new PR with the same changes. https://github.com/patientslikeme/post_pusher/pull/12

Do you have any other suggestions to resolve this issue? It happens on Newswire when it runs a post pusher task.

```
/usr/local/bundle/gems/post_pusher-1.2.0/lib/post_pusher/rake_task_runner.rb:37:in 
`mkdir': No such file or directory @ dir_s_mkdir - /home/plm/service/log/post_push (Errno::ENOENT)
```

**Comment by bryanalves** [comment]
No, I'm just disclosing the potential security issue due to the sensitive information in the public log file that was posted.

**Comment by powerwlsl** [comment]
Oh, I see. I will fix that. Thanks!

**Pull request merged**
